############################
## Author
############################
author:
  name: "Yuma Ishikawa"
  image: me.jpeg
  greeting: "🍶 🐳 ⚽"
  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/yumafuu
  - x-twitter: https://x.com/yuma_katameoome
  - facebook: https://www.facebook.com/yuma.ishikawa.927/
  - c-zenn: https://zenn.dev/yumafuu

################################
### OpenGraph & Twitter Cards
################################

#title: "Qubt Theme"
#description: "Demo site build with Hugo"
#images:
#  - thumbnail.jpeg
